  version: '3.9'

  services:

    pgadmin4:

      hostname: pgadmin4
      container_name: pgadmin4  
      image: dpage/pgadmin4:latest
      environment:
         - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}"
         - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}" 
         - "PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10"
      restart: always
      volumes:
        - '/etc/localtime:/etc/localtime'
        - '/data/storage:/var/lib/pgadmin/storage'