version: '3.9'

services:

   geoserver:
      hostname: lapig-geoserver
      container_name: lapig-geoserver
      image: lapig-geoserver:latest
      networks:
        rede_lapig:
           ipv4_address: 172.18.0.25
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
        - /etc/letsencrypt:/etc/certs
        - /data/storage:/STORAGE
      ports:
        - 127.0.0.1:8443:8443
      expose: 
         - '8443'  
      restart: on-failure
      environment:
        - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
        - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
        - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
        - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
        - INITIAL_MEMORY=${INITIAL_MEMORY}
        - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
        - SSL=true
        - PKCS12_PASSWORD=whateverest
        - JKS_KEY_PASSWORD=whateverest
        - JKS_STORE_PASSWORD=whateverest
        - LETSENCRYPT_CERT_DIR=/etc/certs/live/qghome.duckdns.org
        - ENCODING='UTF8'
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3

volumes:
   geoserver-data:

networks:
    rede_lapig:
      external: true
      driver: bridge