version: '3.9'

volumes:
   geoserver-data:

services:
   nginx:
     image: nginx
     volumes:
       - nginx.conf:/etc/nginx/conf.d:ro
     logging:
       driver: json-file
       options:
         max-size: 200m
         max-file: '10'
     depends_on:
       - geoserver
     ports:
       - "80:80"

