version: "3.8"

services: 
  jupyter_lab:
    container_name: jupyter_lab
    build: .
    restart: always
    ports: 
      - "8888:8888"
    environment: 
      - JUPYTER_ENABLE_LAB=yes
      - JPASSWORD='12345678'
    volumes: 
      - /docker/jupyter:/home/jovyan


volumes:
  jupyter-data:
