version: '3.9'

volumes:
   geoserver-cluster-data:
   geo-db-data:

services:
   db:
      image: kartoza/postgis:13-3.1
      volumes:
        - geo-db-data:/var/lib/postgresql
      environment:
        - POSTGRES_DB=gis
        - POSTGRES_USER=docker
        - POSTGRES_PASS=docker
        - ALLOW_IP_RANGE=0.0.0.0/0
        - FORCE_SSL=TRUE
      restart: on-failure
      healthcheck:
        test: "pg_isready -d gis"
   master:
      image: kartoza/geoserver:2.19.2
      volumes:
         - geoserver-cluster-data:/opt/geoserver/data_dir
      ports:
        - "8081:8080"
      environment:
        - BROKER_URL=tcp://0.0.0.0:61661
        - READONLY=disabled
        - CLUSTER_DURABILITY=false
        - CLUSTERING=True
        - TOGGLE_MASTER=true
        - TOGGLE_SLAVE=true
        - DB_BACKEND=POSTGRES
        - HOST=db
        - POSTGRES_PORT=5432
        - POSTGRES_DB=gis
        - POSTGRES_USER=docker
        - POSTGRES_PASS=docker
        - SSL_MODE=allow
      restart: on-failure
      depends_on:
        db:
          condition: service_healthy
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3
   node:
      image: kartoza/geoserver:2.19.2
      volumes:
         - geoserver-cluster-data:/opt/geoserver/data_dir
      ports:
        - "8082:8080"
      environment:
        - BROKER_URL=tcp://master:61661
        - READONLY=disabled
        - CLUSTER_DURABILITY=false
        - CLUSTERING=True
        - TOGGLE_MASTER=true
        - TOGGLE_SLAVE=true
        - EMBEDDED_BROKER=disabled
      restart: on-failure
      depends_on:
        master:
          condition: service_healthy
        db:
          condition: service_healthy
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3

   

