version: "3.9"

services:

  minio:
    build: .
    hostname: minio
    container_name: minio
    environment:
        - "MINIO_ROOT_USER=${MINIO_ROOT_USER}"
        - "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}"
    restart: on-failure 
    ports:
      - '9001:9001'
    expose:
      - '9001'
    volumes:
        - minio-data:/mnt/data

volumes:
  minio-data:
