  version: '3.9'

  services:
    vault:
        hostname: vault-server
        container_name: vault-server
        image: vault:latest
        restart: always
        networks:
            frontend:
                ipv4_address: 172.10.0.5
        ports:
          - "8200:8200"
        expose:
          - "8200"
        volumes:
          - vault-data:/vault/data
          - vault-logs:/vault/logs
          - vault-file:/vault/file
          - './config.hcl:/etc/vault/config.hcl' 
          - '/etc/localtime:/etc/localtime'
        cap_add:
           - IPC_LOCK
        entrypoint: vault server -config=/etc/vault/config.hcl
  networks:
    frontend:
      ipam:
        config:
          - subnet: 172.10.0.0/24
  volumes:
    vault-data:
    vault-logs:
    vault-file: