version: '3.7'
services:

  geonetwork:
    hostname: geonetwork
    container_name: geonetwork  
    image: geonetwork:3.10.8
    restart: always
    networks:
       rede_lapig:
    ports:
      - 8080:8080
    environment:
      DATA_DIR: /var/lib/geonetwork_data
      POSTGRES_DB_HOST: 172.18.0.4
      POSTGRES_DB_NAME: geonetwork
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_USERNAME: postgres 
      POSTGRES_DB_PASSWORD: Postgres2018!  
      ES_HOST: NONE
    volumes:
      - /home/user/GeonetWork/APP:/var/lib/geonetwork_data
networks:
    rede_lapig:
      external: true
      driver: bridge
volumes:
  geonetwork:
